# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0002_auto_20160706_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUserInfo',
            fields=[
                ('family_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('locale', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('given_name', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('verified_email', models.CharField(max_length=200)),
            ],
        ),
    ]
