# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0003_googleuserinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('is_new', models.BooleanField()),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='no_token', max_length=200),
            preserve_default=False,
        ),
    ]
